---
- name: Install package to manage Mac App Store
  package:
    name: argon/mas/mas
    state: present
  when: ansible_os_family == "Darwin"

- name: Sign in to Mac App Store
  command: mas signin "{{ apple_id }}" "{{ apple_id_password }}"
  when: ansible_os_family == "Darwin" and apple_id != "" and apple_id_password != ""
